version: '3.8'

services:
  rag-app:
    build: .
    ports:
      - "5001:5001"
    volumes:
      - ./uploads:/app/uploads
      - ollama-models:/root/.ollama
    environment:
      - FLASK_ENV=production
      - SECRET_KEY=${SECRET_KEY:-your-secret-key-here}
    depends_on:
      - ollama
    networks:
      - rag-network
    restart: unless-stopped

  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    volumes:
      - ollama-models:/root/.ollama
    networks:
      - rag-network
    # Nota: Ollama ha bisogno di modelli scaricati
    # Puoi aggiungere un comando per scaricare modelli al primo avvio

volumes:
  ollama-models:
    driver: local

networks:
  rag-network:
    driver: bridge